In [1]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)

print("Mean:", mean_val)
print("Std Dev:", std_val)

Sofia Joyce Olis's Array: [14 27 13 24 28 29 44 24 37  8]
Mean: 24.8
Std Dev: 10.43839068055991


In [2]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3, 4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

print("Row sums:", row_sums)
print("Column sums:", col_sums)

Sofia Joyce Olis's Matrix:
 [[14 55 27 13]
 [28 24 24 22]
 [28 29 44 23]]
Row sums: [109  98 124]
Column sums: [ 70 108  95  58]


In [3]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3, 3, 3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:, 1, :]
print("Slice[:,1,:]:\n", slice_mid)

Sofia Joyce Olis's 3D Array:
 [[[13 22 12]
  [23 23 21]
  [11 22 23]]

 [[ 4  7  4]
  [12 10 20]
  [16  7 22]]

 [[25 10  4]
  [13 11 22]
  [24  2 17]]]
Slice[:,1,:]:
 [[23 23 21]
 [12 10 20]
 [13 11 22]]


In [4]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Sofia Joyce Olis's Original: [14 27 13 24 28 29 44 24 37  8]
Filtered subset: []


In [5]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[14 55]
 [27 13]]
Matrix B:
 [[28 24]
 [24 22]]
A @ B:
 [[1712 1546]
 [1068  934]]
Determinant of A: -1303.0


In [6]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

angles = np.linspace(0, 2 * np.pi, 8)

sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Sofia Joyce Olis's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [7]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4, 4))

arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Sofia Joyce Olis's Modified 4x4 Array:
 [[ 0 55  0 13]
 [28 24 24 22]
 [ 0 29  0 23]
 [24 37  8 37]]


In [8]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)

grades = np.where(scores >= STUDENT_ID % 70, "Pass", "Fail")

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Sofia Joyce Olis's Scores: [13 26 12 23 85 27 28 43 23 36]
Grades: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [9]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3, 4))

flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[14 55 27 13]
 [28 24 24 22]
 [28 29 44 23]]
Flattened: [14 55 27 13 28 24 24 22 28 29 44 23]
Transposed:
 [[14 28 28]
 [55 24 29]
 [27 24 44]
 [13 22 23]]


In [10]:
import numpy as np

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3, 3))

mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 55 27]
 [13 -1 -1]
 [-1 -1 -1]]


In [11]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "Name": [STUDENT_NAME] * 5,
    "Score": np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    "YearsCodePro": np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

print(df)

               Name  Score  YearsCodePro
0  Sofia Joyce Olis     49            23
1  Sofia Joyce Olis     62            21
2  Sofia Joyce Olis     48            11
3  Sofia Joyce Olis     63            22
4  Sofia Joyce Olis     59            23


In [12]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "EdLevel": ["Bachelor", "Master", "PhD", "Bachelor", "Master"],
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby("EdLevel")["ConvertedComp"].mean()

print(avg_salary)

EdLevel
Bachelor    94220.5
Master      88296.5
PhD         53978.0
Name: ConvertedComp, dtype: float64


In [13]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "Country": ["Philippines", "USA", "UK", "Canada", "Germany"],
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by="ConvertedComp", ascending=False)

print(top5)

       Country  ConvertedComp
4      Germany         122139
0  Philippines          99277
3       Canada          89164
1          USA          54454
2           UK          53978


In [14]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "Name": [STUDENT_NAME] * 5,
    "YearsCodePro": np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

high_exp = df[df["YearsCodePro"] > STUDENT_ID % 10]

print(high_exp)

               Name  YearsCodePro
0  Sofia Joyce Olis            13
1  Sofia Joyce Olis            22
2  Sofia Joyce Olis            12
3  Sofia Joyce Olis            23
4  Sofia Joyce Olis            23


In [15]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

bins = [0, 50000, 100000, 150000, 200000]
labels = ["0-50k", "50-100k", "100-150k", ">150k"]

df["Bracket"] = pd.cut(df["ConvertedComp"], bins=bins, labels=labels)

print(df)

   ConvertedComp   Bracket
0          99277   50-100k
1          54454   50-100k
2          53978   50-100k
3          89164   50-100k
4         122139  100-150k


In [18]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

df["LogComp"] = np.log(df["ConvertedComp"])

print(df)

   ConvertedComp    LogComp
0          99277  11.505669
1          54454  10.905112
2          53978  10.896332
3          89164  11.398233
4         122139  11.712915


In [17]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "YearsCodePro": np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()

print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.485584
ConvertedComp      0.485584       1.000000


In [23]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "EdLevel": ["Bachelor", "Master", "PhD", "Bachelor", "Master"],
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

summary = df.groupby("EdLevel")["ConvertedComp"].agg(["mean", "median", "std"]).reset_index()

print(summary)

    EdLevel     mean   median           std
0  Bachelor  94220.5  94220.5   7150.970878
1    Master  88296.5  88296.5  47860.522485
2       PhD  53978.0  53978.0           NaN


In [24]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

threshold = 110000

df["HighPay"] = np.where(df["ConvertedComp"] > threshold, "Yes", "No")

print(df)

   ConvertedComp HighPay
0          99277      No
1          54454      No
2          53978      No
3          89164      No
4         122139     Yes


In [25]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Sofia Joyce Olis"
STUDENT_ID = 1136

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    "Country": ["Philippines", "USA", "UK", "Canada", "Germany"],
    "ConvertedComp": np.random.randint(40000, 150000, 5)
})

top_countries = df.groupby("Country")["ConvertedComp"].agg(["mean", "max"])

print(top_countries)

                 mean     max
Country                      
Canada        89164.0   89164
Germany      122139.0  122139
Philippines   99277.0   99277
UK            53978.0   53978
USA           54454.0   54454
