In [17]:
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70],
                     [80, 90, 100]])
print("Salary Matrix:\n", salaries)

zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))

print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#TRY IT
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10, 67, 76])
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70, 99, 89],
                     [80, 90, 100, 87, 56]])
print("Salary Matrix:\n", salaries)

zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))

print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

identity_matrix = np.eye(3)
print(identity_matrix)

Years of Experience: [ 1  3  5  7 10 67 76]
Salary Matrix:
 [[ 50  60  70  99  89]
 [ 80  90 100  87  56]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
exp_plus_5 = years_exp + 5
print("Years + 5:", exp_plus_5)

exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)

sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])

dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [39]:
#TRY IT
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70],
                     [80, 90, 100]])
print("Salary Matrix:\n", salaries)

zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))

print("Years - 2:", years_exp - 2)
print("Years / 2:", years_exp / 2)
print("Exponential:", np.exp(years_exp))
print("Log:", np.log(years_exp))

print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Years - 2: [-1  1  3  5  8]
Years / 2: [0.5 1.5 2.5 3.5 5. ]
Exponential: [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04]
Log: [0.         1.09861229 1.60943791 1.94591015 2.30258509]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
print("First year of experience:", years_exp[0])
print("First two salaries:", salaries[0, :2])
print("Second column salaries:", salaries[:, 1])
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [40]:
#TRY IT
print("First year of experience:", years_exp[0])
print("First two salaries:", salaries[0, :2])
print("Second column salaries:", salaries[:, 1])
print("Last year of experience:", years_exp[-1])
print("Reversed:", years_exp[::-1])
print("Sub-salary block:\n", salaries[:1, :2])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10
Reversed: [10  7  5  3  1]
Sub-salary block:
 [[50 60]]


In [4]:
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Array:\n", reshaped_exp)

flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

print("Transposed Array:\n", reshaped_exp.T)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [41]:
#TRY IT
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Array:\n", reshaped_exp)

flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

print("Transposed Array:\n", reshaped_exp.T)

reshaped = np.reshape(np.arange(1, 10), (3, 3))
print(reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [42]:
#TRY IT
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus

scale = 2
print("Scaled salaries:\n", salaries * scale)
print("Salaries after bonus:\n", salaries_with_bonus)

Scaled salaries:
 [[100 120 140]
 [160 180 200]]
Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [6]:
print("Mean experience:", np.mean(years_exp))
print("Std deviation:", np.std(years_exp))

print("Max salary:", np.max(salaries))
print("Min salary:", np.min(salaries))

print("Sum of salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation: 3.1240998703626617
Max salary: 100
Min salary: 50
Sum of salaries: 450


In [43]:
#TRY IT
print("Mean experience:", np.mean(years_exp))
print("Std deviation:", np.std(years_exp))

print("Max salary:", np.max(salaries))
print("Min salary:", np.min(salaries))

print("Sum of salaries:", np.sum(salaries))

print("Median:", np.median(years_exp))
print("Percentile:", np.percentile(years_exp, 50))

Mean experience: 5.2
Std deviation: 3.1240998703626617
Max salary: 100
Min salary: 50
Sum of salaries: 450
Median: 5.0
Percentile: 5.0


In [7]:
angles = np.array([0, np.pi/4, np.pi/2])

print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Row sums:", salary_sums)

Sine: [0.         0.70710678 1.        ]
Cosine: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Row sums: [180 270]


In [44]:
#TRY IT
angles = np.array([0, np.pi/4, np.pi/2])

print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Row sums:", salary_sums)

print("Square root:", np.sqrt(years_exp))
print("Square:", np.square(years_exp))

Sine: [0.         0.70710678 1.        ]
Cosine: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Row sums: [180 270]
Square root: [1.         1.73205081 2.23606798 2.64575131 3.16227766]
Square: [  1   9  25  49 100]


In [8]:
import pandas as pd

data = np.random.randint(1, 50, size=(5, 3))
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])

print(df_data)
print(df_data.corr())

    X   Y   Z     Log_X    Sqrt_Y
0  30  46  28  3.401197  6.782330
1  24  40  47  3.178054  6.324555
2  31  21  44  3.433987  4.582576
3  47  11  40  3.850148  3.316625
4  39  41  38  3.663562  6.403124
               X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.616610 -0.167257  0.994729 -0.652808
Y      -0.616610  1.000000 -0.399854 -0.586683  0.997046
Z      -0.167257 -0.399854  1.000000 -0.218802 -0.352399
Log_X   0.994729 -0.586683 -0.218802  1.000000 -0.620285
Sqrt_Y -0.652808  0.997046 -0.352399 -0.620285  1.000000


In [45]:
#TRY IT
import pandas as pd

data = np.random.randint(1, 50, size=(5, 3))
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])

print(df_data)
print(df_data.corr())

df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
print(df_imported)

    X   Y   Z     Log_X    Sqrt_Y
0  36   6   6  3.583519  2.449490
1  39  31   4  3.663562  5.567764
2  37  41  24  3.610918  6.403124
3  32  48  49  3.465736  6.928203
4  21  12   3  3.044522  3.464102
               X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.337873  0.093529  0.997517  0.322920
Y       0.337873  1.000000  0.808421  0.365306  0.994169
Z       0.093529  0.808421  1.000000  0.153528  0.747163
Log_X   0.997517  0.365306  0.153528  1.000000  0.343632
Sqrt_Y  0.322920  0.994169  0.747163  0.343632  1.000000
    X   Y   Z     Log_X    Sqrt_Y  Sum_XY
0  48  39  22  3.871201  6.244998      87
1  18  46  25  2.890372  6.782330      64
2  26  18  35  3.258097  4.242641      44
3   2  26   5  0.693147  5.099020      28
4  10  18  41  2.302585  4.242641      28


In [48]:
import pandas as pd

df_data = pd.DataFrame({
    'X': [1, 2, 3, 4],
    'Y': [5, 6, 7, 8]
})

df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())


Data saved to 'sample_data.csv'.
Imported DataFrame:
    X  Y
0  1  5
1  2  6
2  3  7
3  4  8
Summary Statistics:
               X         Y
count  4.000000  4.000000
mean   2.500000  6.500000
std    1.290994  1.290994
min    1.000000  5.000000
25%    1.750000  5.750000
50%    2.500000  6.500000
75%    3.250000  7.250000
max    4.000000  8.000000
Column Means:
 X    2.5
Y    6.5
dtype: float64
Column Standard Deviations:
 X    1.290994
Y    1.290994
dtype: float64


In [49]:
#TRY IT
import pandas as pd

df_data = pd.DataFrame({
    'X': [1, 2, 3, 4],
    'Y': [5, 6, 7, 8]
})

df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
print("Updated DataFrame:\n", df_imported)

df_imported.to_csv('modified_data.csv', index=False)
print("Modified data saved to 'modified_data.csv'.")

Data saved to 'sample_data.csv'.
Imported DataFrame:
    X  Y
0  1  5
1  2  6
2  3  7
3  4  8
Summary Statistics:
               X         Y
count  4.000000  4.000000
mean   2.500000  6.500000
std    1.290994  1.290994
min    1.000000  5.000000
25%    1.750000  5.750000
50%    2.500000  6.500000
75%    3.250000  7.250000
max    4.000000  8.000000
Column Means:
 X    2.5
Y    6.5
dtype: float64
Column Standard Deviations:
 X    1.290994
Y    1.290994
dtype: float64
Updated DataFrame:
    X  Y  Sum_XY
0  1  5       6
1  2  6       8
2  3  7      10
3  4  8      12
Modified data saved to 'modified_data.csv'.


In [11]:
from google.colab import files
uploaded = files.upload()

Saving survey_results_public.csv.zip to survey_results_public.csv.zip


In [32]:
import pandas as pd
import numpy as np
import zipfile

# Unzip the file first
with zipfile.ZipFile('survey_results_public.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('.')

df_kaggle = pd.read_csv('survey_results_public.csv')

# Create df_subset as a copy to avoid SettingWithCopyWarning
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']].copy()

# Convert YearsCodePro to numeric safely
df_subset['YearsCodePro'] = pd.to_numeric(df_subset['YearsCodePro'], errors='coerce')

# Drop missing values and create df_clean as a copy to avoid SettingWithCopyWarning
df_clean = df_subset.dropna().copy()

# Create experience level using .loc to modify df_clean in place
df_clean.loc[:, 'ExperienceLevel'] = np.where(
    df_clean['YearsCodePro'] >= 10,
    'Senior',
    'Junior'
)

# Group and average salary
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()

grouped_data = grouped_data.reset_index()

print(grouped_data.head())

       Country ExperienceLevel  ConvertedCompYearly
0  Afghanistan          Junior         1.031035e+06
1  Afghanistan          Senior         3.300000e+01
2      Albania          Junior         2.564647e+04
3      Albania          Senior         1.397000e+05
4      Algeria          Junior         9.103895e+03


In [38]:
#TRY IT
import pandas as pd
import numpy as np
import zipfile

# Unzip the file first
with zipfile.ZipFile('survey_results_public.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('.')

df_kaggle = pd.read_csv('survey_results_public.csv')

# Create df_subset as a copy to avoid SettingWithCopyWarning
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']].copy()

# Convert YearsCodePro to numeric safely
df_subset['YearsCodePro'] = pd.to_numeric(df_subset['YearsCodePro'], errors='coerce')

# Drop missing values and create df_clean as a copy to avoid SettingWithCopyWarning
df_clean = df_subset.dropna().copy()

# Create experience level using .loc to modify df_clean in place
df_clean.loc[:, 'ExperienceLevel'] = np.where(
    df_clean['YearsCodePro'] >= 10,
    'Senior',
    'Junior'
)

# Group and average salary
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()

grouped_data = grouped_data.reset_index()

print(grouped_data.head())

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

median_group = df_clean.groupby('Country')['ConvertedCompYearly'].median()
print(median_group.head())

       Country ExperienceLevel  ConvertedCompYearly
0  Afghanistan          Junior         1.031035e+06
1  Afghanistan          Senior         3.300000e+01
2      Albania          Junior         2.564647e+04
3      Albania          Senior         1.397000e+05
4      Algeria          Junior         9.103895e+03
Country
Afghanistan     1029.5
Albania        13418.5
Algeria         8782.0
Andorra        37481.5
Angola          4302.0
Name: ConvertedCompYearly, dtype: float64
